version: '3'
services:
  db_users:
    image: postgres:16
    ports:
      - "5445:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: users_db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: clear-solution-app
    depends_on:
      - db_users
    ports:
      - "8888:8888"

